import { StyleSheet } from 'react-native';
import { colors } from '../../constants/theme';

export const styles = StyleSheet.create({
  // shared screen pieces
  grow: { flex: 1, gap: 2, minWidth: 0 },
  gap4: { gap: 4 },
  gap6: { gap: 6 },
  gap8: { gap: 8 },
  rowCenter12: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  whiteBg: { backgroundColor: colors.white },
  centerText: { alignItems: 'center' },
  textCenter: { textAlign: 'center' },
  spacer44: { width: 44 },
  small: { color: colors.muted, fontSize: 13 },
  body14: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  headline: { color: colors.ink, fontSize: 17, fontWeight: '700' },
  screenTitle: { color: colors.ink, fontSize: 28, fontWeight: '800', letterSpacing: -0.6, lineHeight: 31 },
  /** Scroll content for a tab screen that sits above the bottom nav. */
  tabContent: { gap: 14, paddingBottom: 124, paddingHorizontal: 18 },
  backHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  emptyCard: { backgroundColor: colors.white, borderRadius: 28, gap: 14, paddingHorizontal: 20, paddingVertical: 24 },
  emptyTitle: { color: colors.ink, fontSize: 19, fontWeight: '800' },
  noteLime: { backgroundColor: colors.pale, borderRadius: 18, flexDirection: 'row', gap: 10, paddingHorizontal: 14, paddingVertical: 12 },
  notePlain: { flexDirection: 'row', gap: 8, paddingHorizontal: 6, paddingVertical: 4 },
  noteText: { color: colors.muted2, flex: 1, fontSize: 12, lineHeight: 17 },
  noteTextLime: { color: colors.greenDark, fontSize: 13, lineHeight: 18 },
  toggle: { backgroundColor: colors.ring, borderRadius: 99, height: 26, padding: 3, width: 42 },
  toggleOn: { backgroundColor: colors.green },
  toggleKnob: { backgroundColor: colors.white, borderRadius: 10, boxShadow: '0 1px 3px rgba(0,0,0,.2)', height: 20, width: 20 },
  toggleKnobOn: { transform: [{ translateX: 16 }] },
  groupTitle: { color: colors.ink, fontSize: 16, fontWeight: '700' },
  emptyGroup: { alignItems: 'center', borderColor: colors.dashed, borderRadius: 24, borderStyle: 'dashed', borderWidth: 1.5, flexDirection: 'row', gap: 12, padding: 16 },
  mealList: { gap: 2, paddingLeft: 46 },
  mealRow: { alignItems: 'center', borderRadius: 14, flexDirection: 'row', gap: 10, paddingHorizontal: 10, paddingVertical: 8 },
  mealRowStatic: { paddingVertical: 7 },
  mealName: { color: colors.ink, fontSize: 14, fontWeight: '600' },
  mealTime: { color: colors.muted2, fontSize: 12 },
  mealCal: { color: '#3f443a', fontSize: 14, fontWeight: '600' },
  flex: { flex: 1 },
  center: { alignItems: 'center', justifyContent: 'center' },
  selfStretch: { alignSelf: 'stretch', marginTop: 6 },
  card: { backgroundColor: colors.white, borderRadius: 24, padding: 16, gap: 10 },
  pill: { alignItems: 'center', borderRadius: 99, flexDirection: 'row', gap: 8, justifyContent: 'center' },
  pillText: { fontSize: 16, fontWeight: '700' },
  pillTextSmall: { fontSize: 15 },
  glow: { boxShadow: '0 8px 18px rgba(127,191,42,.35)' },
  busy: { opacity: 0.6 },
  banner: { backgroundColor: colors.dangerBg, borderRadius: 18, flexDirection: 'row', gap: 10, paddingHorizontal: 14, paddingVertical: 12 },
  bannerAction: { alignItems: 'center', paddingVertical: 10, paddingRight: 10 },
  bannerText: { color: colors.dangerInk, flex: 1, fontSize: 13, lineHeight: 18 },
  bannerRetry: { backgroundColor: colors.white, borderRadius: 99, paddingHorizontal: 14, paddingVertical: 8 },
  bannerRetryText: { color: colors.ink, fontSize: 13, fontWeight: '700' },
  fieldError: { color: colors.dangerText, fontSize: 13, fontWeight: '600' },
  fieldErrorSmall: { fontSize: 12 },
  errorCard: { alignItems: 'center', backgroundColor: colors.white, borderRadius: 28, gap: 12, padding: 24 },
  errorTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', textAlign: 'center' },
  errorBody: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: 'center' },
  toast: { alignItems: 'center', alignSelf: 'center', backgroundColor: colors.ink, borderRadius: 99, flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 10, position: 'absolute', zIndex: 80 },
  toastText: { color: colors.white, fontSize: 14, fontWeight: '600' },
  inputShell: { alignItems: 'center', backgroundColor: colors.bg, borderRadius: 16, borderWidth: 1.5, borderColor: 'transparent', flexDirection: 'row', height: 52, paddingHorizontal: 16 },
  inputShellError: { borderColor: colors.danger },
  input: { color: colors.ink, flex: 1, fontSize: 18, fontWeight: '700', minWidth: 0, padding: 0 },
  ring: { height: 112, width: 112 },
  ringNum: { color: colors.ink, fontSize: 22, fontWeight: '800' },
  ringLabel: { color: colors.greenDark, fontSize: 11, fontWeight: '600' },
  ringLabelOver: { color: colors.overText, fontWeight: '700' },
  scrimSheet: { backgroundColor: 'rgba(28,31,26,.38)' },
  scrimDialog: { backgroundColor: 'rgba(28,31,26,.42)' },
  macro: { backgroundColor: 'rgba(255,255,255,.75)', borderRadius: 16, flex: 1, gap: 6, paddingHorizontal: 12, paddingVertical: 10 },
  macroLabel: { color: colors.muted, fontSize: 12 },
  macroValue: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  macroUnit: { color: colors.muted, fontSize: 11, fontWeight: '500' },
  macroTrack: { borderRadius: 9, height: 5, overflow: 'hidden' },
  macroFill: { borderRadius: 9, height: '100%' },
  sheet: { backgroundColor: colors.white, borderTopLeftRadius: 32, borderTopRightRadius: 32, bottom: 0, left: 0, maxHeight: '91%', position: 'absolute', right: 0 },
  dialog: { backgroundColor: colors.white, borderRadius: 32, bottom: 30, gap: 12, left: 14, paddingBottom: 20, paddingHorizontal: 22, paddingTop: 24, position: 'absolute', right: 14 },
});
